/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface OtpInput {
        "characterCount": number;
    }
}
declare global {
    interface HTMLOtpInputElement extends Components.OtpInput, HTMLStencilElement {
    }
    var HTMLOtpInputElement: {
        prototype: HTMLOtpInputElement;
        new (): HTMLOtpInputElement;
    };
    interface HTMLElementTagNameMap {
        "otp-input": HTMLOtpInputElement;
    }
}
declare namespace LocalJSX {
    interface OtpInput {
        "characterCount"?: number;
        "onCodeChanged"?: (event: CustomEvent<string>) => void;
    }
    interface IntrinsicElements {
        "otp-input": OtpInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "otp-input": LocalJSX.OtpInput & JSXBase.HTMLAttributes<HTMLOtpInputElement>;
        }
    }
}
