/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface OtcInput {
        "characterCount": number;
    }
}
declare global {
    interface HTMLOtcInputElement extends Components.OtcInput, HTMLStencilElement {
    }
    var HTMLOtcInputElement: {
        prototype: HTMLOtcInputElement;
        new (): HTMLOtcInputElement;
    };
    interface HTMLElementTagNameMap {
        "otc-input": HTMLOtcInputElement;
    }
}
declare namespace LocalJSX {
    interface OtcInput {
        "characterCount"?: number;
        "onCodeChanged"?: (event: CustomEvent<string>) => void;
    }
    interface IntrinsicElements {
        "otc-input": OtcInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "otc-input": LocalJSX.OtcInput & JSXBase.HTMLAttributes<HTMLOtcInputElement>;
        }
    }
}
